### ISSUE TITLE
BIPED datase

### ISSUE THREAD

**Issue by Muzi010** [xavysp/TEED#19]
I would like to ask how to enhance the BIPED dataset, the download is only 258 sheets. It doesn't correspond to train_pair0.lst, can you share the code for dataset enhancement or the dataset after enhancement.

**Comment by xavysp** [comment]
Hi, you can check  https://github.com/xavysp/MBIPED. There, you can find the augmentation process and the list maker.

Cheers, hope you enjoy using TEED.

Xavier

**Comment by Muzi010** [comment]
Thank you very much, yesterday I have found the link to the enhanced source code for this dataset on the BIPDE website!
