### ISSUE TITLE
this code is not run

### ISSUE THREAD

**Issue by rw1995** [xavysp/TEED#2]
hi, this code is very interesting, but i can not run this demo.
when i  run `python main.py --choose_test_data=-1`, i have this wrong

![2023-08-20 18-48-41屏幕截图](https://github.com/xavysp/TEED/assets/37976371/1790558b-db5a-4bee-b63d-2b5a5644a222)

**Comment by rw1995** [comment]
i have download this dataset, link to [dataset](https://drive.google.com/drive/folders/1lZuvJxL4dvhVGgiITmZsjUJPBBrFI_bM)， but train_pair0.lst is not in this dataset

**Comment by rw1995** [comment]
@xavysp

**Comment by xavysp** [comment]
> @xavysp

Hi, so sorry, I was cleaning the code and I didn't realise the indentation of training data loader.
I have just fixed, please try now.

Xavier
