### ISSUE TITLE
import dataset error

### ISSUE THREAD

**Issue by sixgod696** [xavysp/TEED#3]
When reading a BIPED dataset in JSON format, an error is reported, as shown below

<img width="421" alt="image" src="https://github.com/xavysp/TEED/assets/48515654/3cf8bb1e-16cf-4632-b491-204582bcb560">

**Comment by sixgod696** [comment]
I modified the database file and the import was successful, but I'm not sure which datasets B2, B3, etc. in the datasets.py refer to? The BIPED dataset I downloaded does not contain these, and I hope the author can answer them
<img width="72" alt="image" src="https://github.com/xavysp/TEED/assets/48515654/fd784fe1-5ae6-4dd8-b7dc-e8d4fd265ea0">

**Comment by xavysp** [comment]
> When reading a BIPED dataset in JSON format, an error is reported, as shown below
> 
> <img alt="image" width="421" src="https://user-images.githubusercontent.com/48515654/262547296-3cf8bb1e-16cf-4632-b491-204582bcb560.png">

Hi, sorry for my late response. It seems that your json file is empty. I have uploaded my list of training to "TEED/utils/train_pair0.lst", tray opening this file.

Cheers.

**Comment by xavysp** [comment]
Hi, as maybe you can see, results from TEED are thinner than the ones from HED, even DexiNed. So I am preparing the Dollar's code for TEED. In the meantime, try [the evaluation used in DexiNed](https://drive.google.com/file/d/1tm8XJ9VB9LmMFaVNMu9-RGqLFwPxtWiZ/view), with the following modification:
```
tmp_edge = edgesNmsMex(tmp_edge,O,1,5,1.03,8);
```

**Comment by sixgod696** [comment]
> Hi, as maybe you can see, results from TEED are thinner than the ones from HED, even DexiNed. So I am preparing the Dollar's code for TEED. In the meantime, try [the evaluation used in DexiNed](https://drive.google.com/file/d/1tm8XJ9VB9LmMFaVNMu9-RGqLFwPxtWiZ/view), with the following modification:
> 
> ```
> tmp_edge = edgesNmsMex(tmp_edge,O,1,5,1.03,8);
> ```

<img width="444" alt="image" src="https://github.com/xavysp/TEED/assets/48515654/6fbf87b8-8d0e-4cc6-9b50-64859f03ccea">
<img width="556" alt="image" src="https://github.com/xavysp/TEED/assets/48515654/19bcee4a-d997-431a-b129-0cfe37a07574">
I used the evaluation code of the hed integration, I changed your parameters, the image processed by the model was preprocessed to look like this, and the evaluation result remained unchanged. I'm new to MATLAB, and I'm not sure how to use and modify the evaluation code you provided.

**Comment by xavysp** [comment]
Hi, sorry for my late response, I am changing the city, so these days are chaotics. 
So you converted GT images in MAT? I do not remember the BSDS GT mats, but they are binary, (0,1) did you checked that?

**Comment by sixgod696** [comment]
> Hi, sorry for my late response, I am changing the city, so these days are chaotics. So you converted GT images in MAT? I do not remember the BSDS GT mats, but they are binary, (0,1) did you checked that?

Thank you for your reply, I have solved this issue due to my lack of understanding of the edge inspection inspection process, and the test results have been successfully displayed so far.

**Comment by xavysp** [comment]
Oh great, glad your are using TEED.
