### ISSUE TITLE
Application scenarios for edge images

### ISSUE THREAD

**Issue by sixgod696** [xavysp/TEED#4]
What are the specific downstream tasks of edge images generated by edge detection? I noticed that you used it for sketch detection, are there any other specific applications? 
Looking forward to your response.

**Comment by xavysp** [comment]
Hi, sorry for my late response, you can use edge-maps generated with TEED in any task you want. I will thank you tell me how does it go. But, maybe in some downstream tasks, like segmentation (hypothetically speaking) TEED won't be a good choice.

I am preparing an extender version of TEED,  I will use different downstream tasks to compare last SOTA models and TEED. Stay tuned!

Again, sorry for my late response.

Xavier
