### ISSUE TITLE
sizes not match

### ISSUE THREAD

**Issue by Hsssy** [xavysp/TEED#5]
Hi, I am working on another computer vsion field, I am interesting in your research, but When I use TEED as a part of my model, I found a error, It is normal during the train period, but something went wrong during my test period, When test image have different height and weight,here is the error:
![555](https://github.com/xavysp/TEED/assets/81155462/eed2db9c-a990-4dc4-9e27-7c067f17163c)

I want to figure it out what happens, thanks!

**Comment by ewfian** [comment]
```python
img_width = ((image.shape[1] // 16) + 1) * 16
img_height = ((image.shape[0] // 16) + 1) * 16
image = cv2.resize(image, (img_width, img_height))
```
