### ISSUE TITLE
Sketch recognition, JPG to MAT file

### ISSUE THREAD

**Issue by sixgod696** [xavysp/TEED#7]
I used my edge diagram to carry out the sketch recognition project mentioned in the paper, and in order to convert the obtained edge diagram into a suitable MAT file, I wrote a jpg to MAT file script, but the prediction effect was very poor, how did you solve it in the first place?Looking forward to your reply！
![image](https://github.com/xavysp/TEED/assets/48515654/dad26627-dd00-4f85-a2b1-0c8442719297)

**Comment by sixgod696** [comment]
To add, I tried to read the shoe edge data in the default mat format into an image format, and then used my own jpg to mat script. The result was just as bad. I suspected that there was something wrong with the jpg to mat script, but I I’m not familiar with this. How did you solve it in the first place?

**Comment by sixgod696** [comment]
> I used my edge diagram to carry out the sketch recognition project mentioned in the paper, and in order to convert the obtained edge diagram into a suitable MAT file, I wrote a jpg to MAT file script, but the prediction effect was very poor, how did you solve it in the first place?Looking forward to your reply！ ![image](https://private-user-images.githubusercontent.com/48515654/286160089-dad26627-dd00-4f85-a2b1-0c8442719297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTc2NjgsIm5iZiI6MTcwMTE1NzM2OCwicGF0aCI6Ii80ODUxNTY1NC8yODYxNjAwODktZGFkMjY2MjctZGQwMC00Zjg1LWEyYjEtMGM4NDQyNzE5Mjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3NDI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzFhNzQwODdkNWJhZjQ0MmY5ZTMzMmM3NjNjNTc1NmY5MWIzMjgyMDE0MzJmYzcyN2Q4ODI2ZDMxNTlmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zpnN2Qqa0W5YsdZJ7FCcsIDKv7BYDMbF4wBAqucd3Sg)
I have solved this problem, I would like to ask what is the test data size of QMUL-shoe and QMUL-chair you use? Looking forward to your reply

**Comment by sixgod696** [comment]
Excuse me, I have another additional question, that is, my score in top 1 is very low, but my score in top 10 is relatively good. What may be the reason for this? Looking forward to your reply!

**Comment by xavysp** [comment]
Hi @sixgod696 thanks for using our proposal.
Sorry, I may not be able to answer this question. Ww haven't come across this question before. We just replaced the edge map in the original paper with the edge map generated by TEED, and the  code was not changed.

**Comment by sixgod696** [comment]
> Hi @sixgod696 thanks for using our proposal. Sorry, I may not be able to answer this question. Ww haven't come across this question before. We just replaced the edge map in the original paper with the edge map generated by TEED, and the code was not changed.
I understand, thanks for the reply.

**Comment by KinberAlan** [comment]
Hi @sixgod696 ，I encountered some problems in the training process, can you tell me your training parameters ? Thanks very much ! Looking forward to your reply !

**Comment by sixgod696** [comment]
> Hi @sixgod696 ，I encountered some problems in the training process, can you tell me your training parameters ? Thanks very much ! Looking forward to your reply !
I've modified some parts of the network, and I'm not sure which part of your code have the problem.Maybe you can show your error log.

**Comment by KinberAlan** [comment]
> > Hi @sixgod696 ，I encountered some problems in the training process, can you tell me your training parameters ? Thanks very much ! Looking forward to your reply !
> > I've modified some parts of the network, and I'm not sure which part of you are having the problem.

Thank you for your reply！
The first image is the prediction result obtained by using the weight file obtained by my own training, and the second is the prediction result obtained by using the weight file in the source code.The difference is very big, but I don 't know where the problem is.
![1](https://github.com/xavysp/TEED/assets/97089303/5cc44fbf-d008-4e31-b9e9-aafae8540568)
![1](https://github.com/xavysp/TEED/assets/97089303/ea948a79-2aab-466e-b84c-d9d919c3f943)

**Comment by sixgod696** [comment]
> > > Hi @sixgod696 ，I encountered some problems in the training process, can you tell me your training parameters ? Thanks very much ! Looking forward to your reply !
> > > I've modified some parts of the network, and I'm not sure which part of you are having the problem.
> 
> Thank you for your reply！ The first image is the prediction result obtained by using the weight file obtained by my own training, and the second is the prediction result obtained by using the weight file in the source code.The difference is very big, but I don 't know where the problem is. ![1](https://private-user-images.githubusercontent.com/97089303/287221034-5cc44fbf-d008-4e31-b9e9-aafae8540568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMzNjIsIm5iZiI6MTcwMTQyMzA2MiwicGF0aCI6Ii85NzA4OTMwMy8yODcyMjEwMzQtNWNjNDRmYmYtZDAwOC00ZTMxLWI5ZTktYWFmYWU4NTQwNTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MDU0YWZhNWVhNDRlYWE5N2VjZWFlMDFhNThiM2Y4NTE4MzczODJjMjQyOGE4YjQ4NDdkNzJjMjJkZjIxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NN6yjkQUwIoUg-bWo2if2IhHEs8tmHaczy0LKuN0060) ![1](https://private-user-images.githubusercontent.com/97089303/287221100-ea948a79-2aab-466e-b84c-d9d919c3f943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMzNjIsIm5iZiI6MTcwMTQyMzA2MiwicGF0aCI6Ii85NzA4OTMwMy8yODcyMjExMDAtZWE5NDhhNzktMmFhYi00NjZlLWI4NGMtZDlkOTE5YzNmOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YmJlODVmNzQ2N2Y0NGM3NmMxNTY3MDJmZGQ2NDhmN2RiM2RhN2U1YjBjOWE4NDJjMmQ0ZDEyNzYxNjQ0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyf_fJbL2eIDn-5zWaWTv92JLBsar-kZhaxfpL5TQGU)
I have also encountered this problem. You may not have preprocessed the BIPED data set. There is preprocessing code in the BIPED project. After processing, the pictures will increase from hundreds to thousands, so the training time will be normal.

**Comment by KinberAlan** [comment]
> > > > Hi @sixgod696 ，I encountered some problems in the training process, can you tell me your training parameters ? Thanks very much ! Looking forward to your reply !
> > > > I've modified some parts of the network, and I'm not sure which part of you are having the problem.
> > 
> > 
> > Thank you for your reply！ The first image is the prediction result obtained by using the weight file obtained by my own training, and the second is the prediction result obtained by using the weight file in the source code.The difference is very big, but I don 't know where the problem is. ![1](https://private-user-images.githubusercontent.com/97089303/287221034-5cc44fbf-d008-4e31-b9e9-aafae8540568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMzNjIsIm5iZiI6MTcwMTQyMzA2MiwicGF0aCI6Ii85NzA4OTMwMy8yODcyMjEwMzQtNWNjNDRmYmYtZDAwOC00ZTMxLWI5ZTktYWFmYWU4NTQwNTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MDU0YWZhNWVhNDRlYWE5N2VjZWFlMDFhNThiM2Y4NTE4MzczODJjMjQyOGE4YjQ4NDdkNzJjMjJkZjIxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NN6yjkQUwIoUg-bWo2if2IhHEs8tmHaczy0LKuN0060) ![1](https://private-user-images.githubusercontent.com/97089303/287221100-ea948a79-2aab-466e-b84c-d9d919c3f943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMzNjIsIm5iZiI6MTcwMTQyMzA2MiwicGF0aCI6Ii85NzA4OTMwMy8yODcyMjExMDAtZWE5NDhhNzktMmFhYi00NjZlLWI4NGMtZDlkOTE5YzNmOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YmJlODVmNzQ2N2Y0NGM3NmMxNTY3MDJmZGQ2NDhmN2RiM2RhN2U1YjBjOWE4NDJjMmQ0ZDEyNzYxNjQ0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyf_fJbL2eIDn-5zWaWTv92JLBsar-kZhaxfpL5TQGU)
> > I have also encountered this problem. You may not have preprocessed the BIPED data set. There is preprocessing code in the BIPED project. After processing, the pictures will increase from hundreds to thousands, so the training time will be normal.

Because I did not expand the data set to lead to this problem. I did not pay attention to this problem. Thank you very much for taking your time to answer my question, thank you very much ! Wish you have a good day.
